# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imageotd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('image', models.FileField(upload_to='imageotd/%Y/%m/%d')),
                ('date', models.DateField()),
                ('uname', models.CharField(max_length=30)),
            ],
        ),
    ]
