# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-29 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageotd', '0003_auto_20161029_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageotd',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
