# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-30 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageotd', '0004_auto_20161029_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageotd',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='imageotd',
            name='likes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
