# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-02 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageotd', '0006_imageotd_likdisdif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageotd',
            name='image',
            field=models.FileField(blank=True, upload_to='imageotd/%Y/%m/%d'),
        ),
    ]
