# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('writer', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('activity', models.CharField(blank=True, max_length=200)),
                ('season', models.CharField(blank=True, max_length=200)),
                ('trip_area', models.CharField(blank=True, max_length=200)),
                ('elevation_gain', models.CharField(blank=True, max_length=200)),
                ('distance_coverred', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
