# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 19:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0002_auto_20160920_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='time',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
