# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-19 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0005_auto_20160925_0200'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='uname',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
