# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 02:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0006_trail_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='trail',
            name='image',
            field=models.FileField(blank=True, upload_to='trails/%Y/%m/%d'),
        ),
    ]
