# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-19 22:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trails', '0007_trail_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='distance_coverred',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trail',
            name='elevation_gain',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trail',
            name='time',
            field=models.CharField(max_length=200),
        ),
    ]
