# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-20 18:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('report', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reports',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 9, 20, 18, 45, 51, 848003, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reports',
            name='distance_coverred',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='elevation_gain',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reports',
            name='trip_area',
            field=models.TextField(blank=True),
        ),
    ]
