# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-21 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20160920_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
