# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-22 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20160921_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='distance_coverred',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='reports',
            name='elevation_gain',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='reports',
            name='title',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='reports',
            name='trip_area',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AlterField(
            model_name='reports',
            name='writer',
            field=models.CharField(max_length=70),
        ),
    ]
