# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-09-25 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20160923_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reports',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
