# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-16 21:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20160925_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='uname',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
