# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-23 02:15
from __future__ import unicode_literals

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_reports_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='reports',
            name='image',
            field=models.FileField(blank=True, upload_to=reports.models.get_upload_file_name),
        ),
    ]
