# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-10-24 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20161023_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='image',
            field=models.FileField(blank=True, upload_to='reports/%Y/%m/%d'),
        ),
    ]
