# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-13 18:13
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20161024_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
