# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 21:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20161115_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='image',
        ),
    ]
